// SPDX-License-Identifier: Apache-2.0

#include <android/binder_ibinder.h>

#include <cstddef>

// AIDL generated by the Android 16 toolchain registers an optional map used
// only to label Binder transactions in traces. The Android 15 recovery Binder
// runtime predates that API. Keep the A15 runtime ABI instead of replacing
// recovery's Binder stack; transaction dispatch does not depend on this map.
extern "C" void AIBinder_Class_setTransactionCodeToFunctionNameMap(
        AIBinder_Class*, const char**, size_t) {}
